application: ae-python
version: 3
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: webapp2
  version: latest

handlers:
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: favicon\.ico
  mime_type: image/vnd.microsoft.icon

- url: /(.*\.(gif|png|jpg))
  static_files: \1
  upload: (.*\.(gif|png|jpg))

- url: /static/css
  static_dir: static/css

- url: /static/js
  static_dir: static/js

- url: /.*
  script: main.app

